#pragma once

#include "mtype.h"    
#include "CommonK.h"
#include "alFM_v2_1.h"
#include "BVCAM_FACAUTOK/CRSMRKDET_Def.h"
#include <assert.h>

/**
*  \addtogroup alCROSSMARKK
*  @{
*/



/** \brief For default CFG setting. */
#define alCROSSMARKK_MODE_LEFT 0
#define alCROSSMARKK_MODE_RIGHT 0
#define alCROSSMARKK_MODE_FRONT 0
#define alCROSSMARKK_MODE_BACK 0

#define alCROSSMARKK_ROINUM_LEFT 4
#define alCROSSMARKK_ROINUM_RIGHT 4
#define alCROSSMARKK_ROINUM_FRONT 6
#define alCROSSMARKK_ROINUM_BACK 6

// ROI size 
#define alCROSSMARKK_DETECT_ROI_LEFT_W_1 30
#define alCROSSMARKK_DETECT_ROI_LEFT_W_2 30
#define alCROSSMARKK_DETECT_ROI_LEFT_W_3 50
#define alCROSSMARKK_DETECT_ROI_LEFT_W_4 50

#define alCROSSMARKK_DETECT_ROI_LEFT_H_1 20
#define alCROSSMARKK_DETECT_ROI_LEFT_H_2 20
#define alCROSSMARKK_DETECT_ROI_LEFT_H_3 30
#define alCROSSMARKK_DETECT_ROI_LEFT_H_4 30

#define alCROSSMARKK_DETECT_ROI_RIGHT_W_1 30
#define alCROSSMARKK_DETECT_ROI_RIGHT_W_2 30
#define alCROSSMARKK_DETECT_ROI_RIGHT_W_3 50
#define alCROSSMARKK_DETECT_ROI_RIGHT_W_4 50

#define alCROSSMARKK_DETECT_ROI_RIGHT_H_1 20
#define alCROSSMARKK_DETECT_ROI_RIGHT_H_2 20
#define alCROSSMARKK_DETECT_ROI_RIGHT_H_3 30
#define alCROSSMARKK_DETECT_ROI_RIGHT_H_4 30

#define alCROSSMARKK_DETECT_ROI_FRONT_W_1 30
#define alCROSSMARKK_DETECT_ROI_FRONT_W_2 30
#define alCROSSMARKK_DETECT_ROI_FRONT_W_3 30 // 70
#define alCROSSMARKK_DETECT_ROI_FRONT_W_4 30
#define alCROSSMARKK_DETECT_ROI_FRONT_W_5 30
#define alCROSSMARKK_DETECT_ROI_FRONT_W_6 30 // 70

#define alCROSSMARKK_DETECT_ROI_FRONT_H_1 20
#define alCROSSMARKK_DETECT_ROI_FRONT_H_2 20
#define alCROSSMARKK_DETECT_ROI_FRONT_H_3 30
#define alCROSSMARKK_DETECT_ROI_FRONT_H_4 20
#define alCROSSMARKK_DETECT_ROI_FRONT_H_5 20
#define alCROSSMARKK_DETECT_ROI_FRONT_H_6 30

#define alCROSSMARKK_DETECT_ROI_BACK_W_1 30
#define alCROSSMARKK_DETECT_ROI_BACK_W_2 30
#define alCROSSMARKK_DETECT_ROI_BACK_W_3 30 // 50
#define alCROSSMARKK_DETECT_ROI_BACK_W_4 30
#define alCROSSMARKK_DETECT_ROI_BACK_W_5 30
#define alCROSSMARKK_DETECT_ROI_BACK_W_6 30 // 50

#define alCROSSMARKK_DETECT_ROI_BACK_H_1 30
#define alCROSSMARKK_DETECT_ROI_BACK_H_2 30
#define alCROSSMARKK_DETECT_ROI_BACK_H_3 30
#define alCROSSMARKK_DETECT_ROI_BACK_H_4 30
#define alCROSSMARKK_DETECT_ROI_BACK_H_5 30
#define alCROSSMARKK_DETECT_ROI_BACK_H_6 30
// ROI size 


#define alCROSSMARKK_SBV_SCALE_LEFT_1 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_LEFT_2 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_LEFT_3 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_LEFT_4 1.0 // 2.0

#define alCROSSMARKK_SBV_SCALE_RIGHT_1 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_RIGHT_2 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_RIGHT_3 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_RIGHT_4 1.0 // 2.0

#define alCROSSMARKK_SBV_SCALE_FRONT_1 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_FRONT_2 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_FRONT_3 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_FRONT_4 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_FRONT_5 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_FRONT_6 1.0 // 2.0

#define alCROSSMARKK_SBV_SCALE_BACK_1 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_BACK_2 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_BACK_3 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_BACK_4 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_BACK_5 1.0 // 2.0
#define alCROSSMARKK_SBV_SCALE_BACK_6 1.0 // 2.0

#define alCROSSMARKK_SBV_OFFSETX_LEFT_1 -100
#define alCROSSMARKK_SBV_OFFSETX_LEFT_2 -100
#define alCROSSMARKK_SBV_OFFSETX_LEFT_3 -100
#define alCROSSMARKK_SBV_OFFSETX_LEFT_4 -100

#define alCROSSMARKK_SBV_OFFSETX_RIGHT_1 100
#define alCROSSMARKK_SBV_OFFSETX_RIGHT_2 100
#define alCROSSMARKK_SBV_OFFSETX_RIGHT_3 100
#define alCROSSMARKK_SBV_OFFSETX_RIGHT_4 100

#define alCROSSMARKK_SBV_OFFSETX_FRONT_1 -300
#define alCROSSMARKK_SBV_OFFSETX_FRONT_2 -300
#define alCROSSMARKK_SBV_OFFSETX_FRONT_3 -300
#define alCROSSMARKK_SBV_OFFSETX_FRONT_4 300
#define alCROSSMARKK_SBV_OFFSETX_FRONT_5 300
#define alCROSSMARKK_SBV_OFFSETX_FRONT_6 300

#define alCROSSMARKK_SBV_OFFSETX_BACK_1 300
#define alCROSSMARKK_SBV_OFFSETX_BACK_2 300
#define alCROSSMARKK_SBV_OFFSETX_BACK_3 300
#define alCROSSMARKK_SBV_OFFSETX_BACK_4 -300
#define alCROSSMARKK_SBV_OFFSETX_BACK_5 -300
#define alCROSSMARKK_SBV_OFFSETX_BACK_6 -300

//
#define alCROSSMARKK_SBV_OFFSETY_LEFT_1 -300
#define alCROSSMARKK_SBV_OFFSETY_LEFT_2 -300
#define alCROSSMARKK_SBV_OFFSETY_LEFT_3 360
#define alCROSSMARKK_SBV_OFFSETY_LEFT_4 360

#define alCROSSMARKK_SBV_OFFSETY_RIGHT_1 -300
#define alCROSSMARKK_SBV_OFFSETY_RIGHT_2 -300
#define alCROSSMARKK_SBV_OFFSETY_RIGHT_3 360
#define alCROSSMARKK_SBV_OFFSETY_RIGHT_4 360

#define alCROSSMARKK_SBV_OFFSETY_FRONT_1 -100
#define alCROSSMARKK_SBV_OFFSETY_FRONT_2 -100
#define alCROSSMARKK_SBV_OFFSETY_FRONT_3 -100
#define alCROSSMARKK_SBV_OFFSETY_FRONT_4 -100
#define alCROSSMARKK_SBV_OFFSETY_FRONT_5 -100
#define alCROSSMARKK_SBV_OFFSETY_FRONT_6 -100

#define alCROSSMARKK_SBV_OFFSETY_BACK_1 100
#define alCROSSMARKK_SBV_OFFSETY_BACK_2 100
#define alCROSSMARKK_SBV_OFFSETY_BACK_3 100
#define alCROSSMARKK_SBV_OFFSETY_BACK_4 100
#define alCROSSMARKK_SBV_OFFSETY_BACK_5 100
#define alCROSSMARKK_SBV_OFFSETY_BACK_6 100

//
#define alCROSSMARKK_CROSSMARK_OFFSETX_LEFT_1 0
#define alCROSSMARKK_CROSSMARK_OFFSETX_LEFT_2 0
#define alCROSSMARKK_CROSSMARK_OFFSETX_LEFT_3 0 // -25
#define alCROSSMARKK_CROSSMARK_OFFSETX_LEFT_4 0

#define alCROSSMARKK_CROSSMARK_OFFSETY_LEFT_1 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_LEFT_2 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_LEFT_3 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_LEFT_4 0

#define alCROSSMARKK_CROSSMARK_OFFSETX_RIGHT_1 0
#define alCROSSMARKK_CROSSMARK_OFFSETX_RIGHT_2 0
#define alCROSSMARKK_CROSSMARK_OFFSETX_RIGHT_3 0 // 25
#define alCROSSMARKK_CROSSMARK_OFFSETX_RIGHT_4 0

#define alCROSSMARKK_CROSSMARK_OFFSETY_RIGHT_1 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_RIGHT_2 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_RIGHT_3 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_RIGHT_4 0

#define alCROSSMARKK_CROSSMARK_OFFSETX_FRONT_1 0
#define alCROSSMARKK_CROSSMARK_OFFSETX_FRONT_2 0
#define alCROSSMARKK_CROSSMARK_OFFSETX_FRONT_3 0
#define alCROSSMARKK_CROSSMARK_OFFSETX_FRONT_4 0
#define alCROSSMARKK_CROSSMARK_OFFSETX_FRONT_5 0
#define alCROSSMARKK_CROSSMARK_OFFSETX_FRONT_6 0

#define alCROSSMARKK_CROSSMARK_OFFSETY_FRONT_1 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_FRONT_2 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_FRONT_3 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_FRONT_4 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_FRONT_5 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_FRONT_6 0

#define alCROSSMARKK_CROSSMARK_OFFSETX_BACK_1 0
#define alCROSSMARKK_CROSSMARK_OFFSETX_BACK_2 0
#define alCROSSMARKK_CROSSMARK_OFFSETX_BACK_3 0
#define alCROSSMARKK_CROSSMARK_OFFSETX_BACK_4 0
#define alCROSSMARKK_CROSSMARK_OFFSETX_BACK_5 0
#define alCROSSMARKK_CROSSMARK_OFFSETX_BACK_6 0

#define alCROSSMARKK_CROSSMARK_OFFSETY_BACK_1 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_BACK_2 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_BACK_3 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_BACK_4 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_BACK_5 0
#define alCROSSMARKK_CROSSMARK_OFFSETY_BACK_6 0


// LEFT
#define alCROSSMARKK_CROSSMARK_DIFF_TH_LEFT_1 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_LEFT_1 1000
#define alCROSSMARKK_CROSSMARK_VARIN_TH_LEFT_1 1500
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_LEFT_1 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_LEFT_1 3000

#define alCROSSMARKK_CROSSMARK_DIFF_TH_LEFT_2 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_LEFT_2 1000
#define alCROSSMARKK_CROSSMARK_VARIN_TH_LEFT_2 1500
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_LEFT_2 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_LEFT_2 3000

#define alCROSSMARKK_CROSSMARK_DIFF_TH_LEFT_3 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_LEFT_3 2000
#define alCROSSMARKK_CROSSMARK_VARIN_TH_LEFT_3 2000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_LEFT_3 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_LEFT_3 450

#define alCROSSMARKK_CROSSMARK_DIFF_TH_LEFT_4 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_LEFT_4 2000
#define alCROSSMARKK_CROSSMARK_VARIN_TH_LEFT_4 2000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_LEFT_4 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_LEFT_4 450

// RIGHT
#define alCROSSMARKK_CROSSMARK_DIFF_TH_RIGHT_1 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_RIGHT_1 1000
#define alCROSSMARKK_CROSSMARK_VARIN_TH_RIGHT_1 1500
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_RIGHT_1 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_RIGHT_1 3000

#define alCROSSMARKK_CROSSMARK_DIFF_TH_RIGHT_2 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_RIGHT_2 1000
#define alCROSSMARKK_CROSSMARK_VARIN_TH_RIGHT_2 1500
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_RIGHT_2 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_RIGHT_2 3000

#define alCROSSMARKK_CROSSMARK_DIFF_TH_RIGHT_3 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_RIGHT_3 2000
#define alCROSSMARKK_CROSSMARK_VARIN_TH_RIGHT_3 2000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_RIGHT_3 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_RIGHT_3 450

#define alCROSSMARKK_CROSSMARK_DIFF_TH_RIGHT_4 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_RIGHT_4 2000
#define alCROSSMARKK_CROSSMARK_VARIN_TH_RIGHT_4 2000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_RIGHT_4 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_RIGHT_4 450

// FRONT
#define alCROSSMARKK_CROSSMARK_DIFF_TH_FRONT_1 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_FRONT_1 800
#define alCROSSMARKK_CROSSMARK_VARIN_TH_FRONT_1 1000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_FRONT_1 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_FRONT_1 450

#define alCROSSMARKK_CROSSMARK_DIFF_TH_FRONT_2 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_FRONT_2 800
#define alCROSSMARKK_CROSSMARK_VARIN_TH_FRONT_2 1000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_FRONT_2 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_FRONT_2 450

#define alCROSSMARKK_CROSSMARK_DIFF_TH_FRONT_3 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_FRONT_3 800
#define alCROSSMARKK_CROSSMARK_VARIN_TH_FRONT_3 1000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_FRONT_3 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_FRONT_3 450

#define alCROSSMARKK_CROSSMARK_DIFF_TH_FRONT_4 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_FRONT_4 800
#define alCROSSMARKK_CROSSMARK_VARIN_TH_FRONT_4 1000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_FRONT_4 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_FRONT_4 450

#define alCROSSMARKK_CROSSMARK_DIFF_TH_FRONT_5 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_FRONT_5 800
#define alCROSSMARKK_CROSSMARK_VARIN_TH_FRONT_5 1000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_FRONT_5 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_FRONT_5 450

#define alCROSSMARKK_CROSSMARK_DIFF_TH_FRONT_6 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_FRONT_6 800
#define alCROSSMARKK_CROSSMARK_VARIN_TH_FRONT_6 1000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_FRONT_6 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_FRONT_6 450

// BACK
#define alCROSSMARKK_CROSSMARK_DIFF_TH_BACK_1 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_BACK_1 800
#define alCROSSMARKK_CROSSMARK_VARIN_TH_BACK_1 1000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_BACK_1 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_BACK_1 450

#define alCROSSMARKK_CROSSMARK_DIFF_TH_BACK_2 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_BACK_2 800
#define alCROSSMARKK_CROSSMARK_VARIN_TH_BACK_2 1000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_BACK_2 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_BACK_2 450

#define alCROSSMARKK_CROSSMARK_DIFF_TH_BACK_3 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_BACK_3 800
#define alCROSSMARKK_CROSSMARK_VARIN_TH_BACK_3 1000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_BACK_3 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_BACK_3 450

#define alCROSSMARKK_CROSSMARK_DIFF_TH_BACK_4 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_BACK_4 800
#define alCROSSMARKK_CROSSMARK_VARIN_TH_BACK_4 1000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_BACK_4 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_BACK_4 450

#define alCROSSMARKK_CROSSMARK_DIFF_TH_BACK_5 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_BACK_5 800
#define alCROSSMARKK_CROSSMARK_VARIN_TH_BACK_5 1000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_BACK_5 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_BACK_5 450

#define alCROSSMARKK_CROSSMARK_DIFF_TH_BACK_6 90
#define alCROSSMARKK_CROSSMARK_VARIN_DTAIL_TH_BACK_6 800
#define alCROSSMARKK_CROSSMARK_VARIN_TH_BACK_6 1000
#define alCROSSMARKK_CROSSMARK_VAROUT_TH_BACK_6 1500
#define alCROSSMARKK_CROSSMARK_VAR_TH_BACK_6 450


#define alCROSSMARKK_MAX_ROI 8
#define alCROSSMARKK_MAX_POINT 1
#define alCROSSMARKK_MAX_REGION_NUM 2
#define alCROSSMARKK_MAX_POINT_NUM_REGION 4

#ifdef __cplusplus
extern "C"
{
#endif

	/** \brief The point struct for recording X, Y position of points. */
	typedef struct
	{
		FLOAT64   eX;
		FLOAT64   eY;
	} alCROSSMARKK_Point;

	/** \brief The vector struct for recording start and end points. */
	typedef struct
	{
		alCROSSMARKK_Point   tStart;
		alCROSSMARKK_Point   tEnd;
	} alCROSSMARKK_Vector;

	/** \brief Define the RectK configure data struct . */
	typedef struct
	{
		/** \brief Scale of SBV, 2 set for each view*/
		FLOAT64 aeSBVScale;

		/** \brief x offset of SBV, 2 set for each view*/
		INT32 alSBVOffsetX;

		/** \brief y offset of SBV, 2 set for each view*/
		INT32 alSBVOffsetY;

		/** \brief x offset of detect position (for CrossMark)*/
		INT32 lSBVDetectOffsetX;

		/** \brief y offset of detect position (for CrossMark)*/
		INT32 lSBVDetectOffsetY;

        /** \brief Detect ROI size*/
        alPointINT32 tROISize;

	} alCROSSMARKK_ROICfg;

	/** \brief Define the RectK configure data struct . */
	typedef struct
	{
		/** \brief ROI Number in view*/
		INT32 lROINum;

		/** \brief Mode of K 0: 6個點   1: 4個點*/
		UINT8 ucMode;

		/** \brief Region config in view*/
		alCROSSMARKK_ROICfg atROICfg[alCROSSMARKK_MAX_ROI];

        /** \brief Threshold of Cross Mark detection*/
        alCRSMRKDET_Cfg atCrossMarkDetCfg[alCROSSMARKK_MAX_ROI];

	} alCROSSMARKK_Cfg;

	/** \brief Define the FACTORYAUTOK FACTORYAUTOK_Parameter data struct . */
	typedef struct
	{
		/** \brief Ideal Point of CrossMark K*/
		alPointINT32 atIdealPointCrossMark[alCROSSMARKK_MAX_ROI];

		/** \brief ROI of RecTangle K*/
		alRectINT32 atCrossMarkROI[alCROSSMARKK_MAX_ROI];

		/** \brief Fisheye Model of this view*/
        alFM_v2_1_Model *ptFisheyeModel;

		/** \brief mmpp (mm per pixel)*/
		FLOAT64 eMMPP;

		/** \brief Define the y position limitation to avoid the overflow of calculate BV to original image coordinates. */
		INT32 lOriImgYLimit;

		/** \brief camera angle for transfer SBV to BV. */
		INT32 lAngleCAM;

		/** \brief camera positionX. */
		INT32 lCamPosX;

		/** \brief camera positionY. */
		INT32 lCamPosY;

	} alCROSSMARKK_Parameter;

/*
\brief To load default CFG data.
\param a_lMode [IN] mode
\param alCROSSMARKK_Cfg [IN] configure data
*/
void alCROSSMARKK_LoadDefault(INT32 a_lMode, alCROSSMARKK_Cfg *a_ptCFGData);


#ifdef __cplusplus
}
#endif

/**
*  @}
*/
